# Website settings
url: "https://datageek.pl"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
    kaggle: "https://www.kaggle.com/oskarj"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Oskar Jarczyk"
description: "Description..."
thumbnail_path: "profile-photos/oskar-jarczyk-medium.jpg"

pjait_url: "https://www.pja.edu.pl"
website_repo_url: "https://github.com/oskar-j/oskar-j.github.io"
deepbi_url: "https://www.deep.bi/"
google_scholar_url: "https://scholar.google.pl/citations?user=1-gk3yEAAAAJ&hl=en&oi=ao"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/oskarj86"
    label: "Twitter"
    icon: "twitter-square"
    username: "@oskarj86"
  linkedin:
    url: "https://www.linkedin.com/in/oskarjarczyk"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/social.networking.geek"
    label: "Facebook"
    icon: "facebook-square"
  google:
    url: "https://plus.google.com/"
    label: "Google+"
    icon: "google-plus-square"
  slideshare:
    url: "https://www.slideshare.net/"
    label: "SlideShare"
    icon: "slideshare"
  github:
    url: "https://github.com/oskar-j/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:oskar.jarczyk@gmail.com"
    label: "Email"
    value: "oskar.jarczyk@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: oskar-j/oskar-j.github.io

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
